# Generated by Django 3.1.3 on 2020-11-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['clinic_id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ohip_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinic')),
            ],
            options={
                'ordering': ['ohip_id'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('cpso_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinic')),
            ],
            options={
                'ordering': ['cpso_id'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('full checkup', 'Full Checkup'), ('vitals checkup', 'Vitals Checkup'), ('vaccination', 'Vaccination'), ('prescription refill', 'Prescription Refill'), ('general consultation', 'General Consultation'), ('other', 'Other')], max_length=30)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('duration', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=100)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinic')),
                ('cpso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('ohip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
