# Generated by Django 3.0.6 on 2021-07-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_license',
            new_name='license',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='isLicenseVerified',
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='middleName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
