# Generated by Django 3.0.6 on 2021-07-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20210717_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='middleName',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
