# Generated by Django 3.0.6 on 2021-07-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctortype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctor',
            name='types',
            field=models.ManyToManyField(blank=True, default=None, to='doctors.DoctorType'),
        ),
    ]
