# Generated by Django 3.0.6 on 2021-07-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('appointment_type', models.CharField(max_length=100)),
                ('clinic_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clinics.Clinic')),
                ('doctor_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
                ('patient_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
