# Generated by Django 3.0.6 on 2021-07-18 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_clinic_doctors'),
        ('doctors', '0003_auto_20210717_2324'),
        ('appointments', '0002_auto_20210717_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('length', models.IntegerField()),
                ('clinic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clinics.Clinic')),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PreAppointmentQuestion',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=50)),
                ('appointment_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointments.AppointmentType')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='clinic_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='endTime',
        ),
        migrations.CreateModel(
            name='PreAppointmentResponses',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('response', models.TextField(blank=True, default='', null=True)),
                ('appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointments.Appointment')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointments.PreAppointmentQuestion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointments.AppointmentType'),
        ),
    ]
