# Generated by Django 3.0.6 on 2021-07-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('isEmailVerified', models.BooleanField(default=False)),
                ('insuranceNumber', models.CharField(max_length=30)),
                ('isInsuranceNumberVerified', models.BooleanField(default=False)),
                ('phoneNumber', models.CharField(default='', max_length=15)),
                ('image', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
