# Generated by Django 3.0.6 on 2021-07-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='isInsuranceNumberVerified',
            new_name='insuranceVerified',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='isEmailVerified',
            new_name='verified',
        ),
        migrations.AddField(
            model_name='patient',
            name='middleName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
