# Generated by Django 3.0.8 on 2021-07-12 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('clinic_license', models.CharField(max_length=30)),
                ('isLicenseVerified', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('doctor_license', models.CharField(max_length=30)),
                ('isLicenseVerified', models.BooleanField(default=False)),
                ('specialty', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(choices=[('ENGLISH', 'English'), ('SPANISH', 'Spanish'), ('FRENCH', 'French'), ('CHINESE', 'Chinese'), ('NEPALI', 'Nepali'), ('GUJURATI', 'Gujurati'), ('HINDI', 'Hindi'), ('RUSSIAN', 'Russian'), ('PORTUGESE', 'Portugese'), ('INODNESIAN', 'Inodnesian'), ('ITALIAN', 'Italian'), ('JAPANESE', 'Japanese'), ('MARATHI', 'Marathi'), ('BENGALI', 'Bengali'), ('TAMIL', 'Tamil'), ('URDU', 'Urdu'), ('SEWDISH', 'Sewdish'), ('KOREAN', 'Korean'), ('IRISH', 'Irish'), ('FINNISH', 'Finnish'), ('DUTCH', 'Dutch'), ('ROMANIAN', 'Romanian'), ('SLOVAK', 'Slovak'), ('UKRAINIAN', 'Ukrainian'), ('TURKISH', 'Turkish')], default='ENGLISH', max_length=10)),
            ],
            options={
                'verbose_name': 'Language',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('isEmailVerified', models.BooleanField(default=False)),
                ('insuranceNumber', models.CharField(max_length=30)),
                ('isInsuranceNumberVerified', models.BooleanField(default=False)),
                ('phoneNumber', models.CharField(default='', max_length=15)),
                ('image', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('appointment_type', models.CharField(max_length=100)),
                ('clinic_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myClinic_api.Clinic')),
                ('doctor_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myClinic_api.Doctor')),
                ('patient_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myClinic_api.Patient')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
