# Generated by Django 3.0.6 on 2021-07-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('clinic_license', models.CharField(max_length=30)),
                ('isLicenseVerified', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
