# Generated by Django 3.0.6 on 2021-07-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='days',
        ),
    ]
