# Generated by Django 3.0.6 on 2021-07-17 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_remove_clinic_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='clinic_license',
            new_name='license',
        ),
    ]
