# Generated by Django 3.0.6 on 2021-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20210717_2324'),
        ('clinics', '0003_auto_20210717_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='doctors',
            field=models.ManyToManyField(default=None, to='doctors.Doctor'),
        ),
    ]
