# Generated by Django 3.0.6 on 2021-08-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_auto_20210718_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
